#pragma once
#include <vulkan/vulkan_core.h>

enum VkExtendedQueueFlagBits{
    GRAPHICS        = VK_QUEUE_GRAPHICS_BIT,
    COMPUTE         = VK_QUEUE_COMPUTE_BIT,
    TRANSFER        = VK_QUEUE_TRANSFER_BIT,
    SPARSE_BINDING  = VK_QUEUE_SPARSE_BINDING_BIT,
    PROTECTED       = VK_QUEUE_PROTECTED_BIT,
    VIDEO_DECODE    = VK_QUEUE_VIDEO_DECODE_BIT_KHR,
    VIDEO_ENCODE    = VK_QUEUE_VIDEO_ENCODE_BIT_KHR,
    OPTICAL_FLOW    = VK_QUEUE_OPTICAL_FLOW_BIT_NV,
    PRESENT         = 0
};